- hosts: localhost
  tasks:
    - template:
        src: test.yml.j2
        dest: /root/jinjapractice/a.yml
        
- name:  Setup the NonProd SailPoint Virtual Appliance
  cloudformation:
    region: ap-south-1
    stack_name: test2
    template: /root/jinjapractice/a.yml
    termination_protection: true
    create_changeset: yes
    disable_rollback: true
