- hosts: localhost
  tasks:
  - name: create stack
    amazon.aws.cloudformation:
      stack_name: "test2"
      region: "ap-south-1"
      template: "/root/jinjapractice/b.yml"
      termination_protection: true
      disable_rollback: true
