- hosts: all
  connection: local
  tasks:
  - name: create stack
    amazon.aws.cloudformation:
      stack_name: "test2"
      template: "/root/jinjapractice/b.yml"
      termination_protection: true
      disable_rollback: true
      create_changeset: yes
      template_parameters:
        Hostname: "{{ hostname }}"
        InstanceType: "{{ instance_type }}"
