- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: expand Jinja 
    template:
      src: "test.yml.j2"
      dest: "/root/jinjapractice/b.yml"
      
  - name: create stack
    amazon.aws.cloudformation:
      stack_name: "test-{{ hostname }}"
      template: "/root/jinjapractice/b.yml"
      termination_protection: true
      disable_rollback: true
      create_changeset: yes
      template_parameters:
        Hostname: "{{ hostname }}"
        InstanceType: "{{ instance_type }}"
      tags:
        name: "{{ hostname }}"
        
