- hosts: localhost
  tasks:
  - name: create stack
    amazon.aws.cloudformation:
      stack_name: "test2"
      template: "/root/jinjapractice/b.yml"
      termination_protection: true
      disable_rollback: true
      template_parameters:
        InstanceType: "t2.micro"
