- hosts: localhost
  tasks:
      amazon.aws.cloudformation:
      region: ap-south-1
      stack_name: test2
      template:
          src:  test.yml.j2
          dest: /root/jinjapractice/b.yml
      termination_protection: true
      create_changeset: yes
      disable_rollback: true
