- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: Assume role
    community.aws.sts_assume_role:
      role_arn: "arn:aws:iam::603651671970:role/ReplatformPipelineBuildRole"
      role_session_name: "someRoleSession"
    register: assumed_role
    
  - name: expand Jinja 
    template:
      src: "test.yml.j2"
      dest: "/root/jinjapractice/b.yml"
    
  - name: error 
    debug:
      msg: "{{ assumed_role.sts_creds.access_key }}"    
      
 
      
  #- name: create stack
   # amazon.aws.cloudformation:
    #  aws_access_key: "{{ assumed_role.sts_creds.access_key }}"
     # aws_secret_key: "{{ assumed_role.sts_creds.secret_key }}"
      #security_token: "{{ assumed_role.sts_creds.session_token }}"
      #stack_name: "test-{{ item.hostname }}"
      #template: "/root/jinjapractice/b.yml"
      #termination_protection: true
      #disable_rollback: true
      #create_changeset: yes
      #template_parameters:
       # Hostname: "{{ item.hostname }}"
        #InstanceType: "{{ item.instance_type }}"
      #tags:
       # owner: "gyan-{{ item.hostname }}"
    #loop: "{{ multiple }}"    
