- hosts: localhost
  connection: local
  gather_facts: true
  tasks: 
  - name: Get summary information about a stack
    amazon.aws.cloudformation_info:
      stack_name: test-ansiblejinjatest1
    register: output
  -debug:
      msg: "{{ output.cloudformation[stack_name] }}"
